import os

import datasets
from src.unitxt.blocks import FormTask, LoadHF, RenameFields, SplitRandomMix, TaskCard
from src.unitxt.catalog import add_to_catalog
from src.unitxt.test_utils.card import test_card

# write here the path to the directory where the data is generated by the .sh script get.sh of the cloned japanese project,
# from https://github.com/Katsumata420/wikihow_japanese
# data has the internal structure:
# data/
#     html/
#     json/
#     output/
#     url/
# we need the files in output/:  dev.jsonl,  test.jsonl, and train.jsonl.
# in here, set the value of path to the full path in the file system down to data/output/
# e.g: path = /home/dafnapension/wikihow_japanese/data/output
#

path = "/home/dafnapension/wikihow_japanese/data/output"

card = TaskCard(
    loader=LoadHF(
        path="json",
        data_files={
            "train": os.path.join(path, "train.jsonl"),
            "validation": os.path.join(path, "dev.jsonl"),
            "test": os.path.join(path, "test.jsonl"),
        },
    ),
    preprocess_steps=[
        RenameFields(field_to_field={"tgt": "question", "src": "answer"}),
    ],
    task=FormTask(
        inputs=["question"],
        outputs=["answer"],
        metrics=["metrics.rouge"],
    ),
    templates="templates.qa.open.all",
)

test_card(card, debug=True)
add_to_catalog(card, "cards.wikihow_summ_jp", overwrite=True)
